name: Publish

on:
    push: 
        tags: 
            - 'v*'
    workflow_dispatch: 

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-push:
        name: Build and Push
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write
        steps:
          - uses: actions/checkout@v4
          - name: Log in to the Container Registry
            uses: docker/login-action@v3
            with:
                registry: ${{ env.REGISTRY }}
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
          - name: Extract Metadata
            id: meta
            uses: docker/metadata-action@v5
            with:
                tags: |
                    type=semver,pattern={{version}}
                image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          - name: Build and Push Docker Image
            id: push
            uses: docker/build-push-action@v5
            with:
                context: .
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                label: ${{ steps.meta.outputs.label }}
          - name: Generate Artifact Attestation
            uses: actions/attest-build-provenance@v2
            with:
                subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
                subject-digest: ${{ steps.push.outputs.digest }}
                push-to-registry: true
